## edit

v <- "ACGGTTCCGAGAGTATTCGTCCGGCGAAGTGAGTGTTCATGGAGTCGCATGGAAACGGATAGGGGCGCGCGGTACCACTAACCGACGTGCGTCGTCTCCAGCCAATGGTAAAGTACACATCCGCGGCAGGATGGCTGACGCGACTGTGCAGCTGCCGAGGAGGTGTGTTTAGATTTCACGATGTATTCCTAATCGCCCAATTTGAACGATAACTAAGGCTCTCATTCCTGCCGGAAGCGTGTATCTTGTCTCGATTTCCTTAGTAGGAGTGCACAACTTAGCGACTAGCACGTGTCGTACAGCACATAGTGTAGACAAGAAATGCGTCAAGAAAGTTTAAAGAAGATGTAACAGATAAAGATTCAAGAAAGGCCGAGCACTATGGAAATAAGTACAAGAGGGACTATCTGCAGCAGTCGATTACGGTGCGACAAGTATGGTACCGGACGAGTGTCCTGCCAGGCTGTTTATTCACGAGTTATACCGAACGACGCAGTTTGACAAAGAGAACTTGTCTCCATGTGGACGTCGAGAGCCGAGTACCAGTTTAAAGGGTTATGAGCGGACTGGCCACACCCCGCTTCCGCACATAAAGCTTCTTATATCCCGGAAGAGGAAAACAACAAAGCCCCTTACTAAATACATCGAGATTGTACAGTTAACTCACCAAGAACCATAATTTCCCGACATGAAGATACTAAAACACATTTAGGGGTGGCGCGTTGGCTCTACCCTTTTCACCTCTGGGTGGGTTAAGAGAACGAGCTCCTTGGCCAGCAAGCTGTGAAACACCTCAAAGTGCGCAGATGTACCCGCGGGATGCGTGTTCATCCGTATAGTGTTTGGCGCCTTCCCGAGGTATTTTCGACCCTGGGGACATGAGGAGCTTGCCTAGGGTTG"
w <- "ACGGTTCCAGGAGACAGTATTGTCCGGCGTTGTTCATGGTATGCACGTCGCGGTTTCTGTATGACGGCGGGGGCTAACCGTGCGTAGCTATAGTACACCCCAGTTCCGGCAGGAGAGTGAAGCTGCTTCTCCCGAGGCGGTGTAAAATATCCCGCGCGCTGTGAAAAGTTGAACGATAACAGCATGCCTGCCGGCAGTGTGTATTGCCCTCGATTTCCTTACTAGGAGTGGCTTGAACTTAGCGACTCAAGTAACACATACTGCGTCAATATGTAGTCAAGAAATGCACCAAAGAAGAAGATGTAACAGATAAAGATTCTGCATACCCCAGAAATATGGAAATAAGTACCTTCGTTATTCCAGGCAGCAGGCAGACATTTCCAAGTATGGAGTGTCCTGCCTTATTCACGAGTTATACCCAACGTCGCAGTTTCACATAGGCGAGATTCTGTGGGCTTGTCTAGCATGTGTACTCGTGCTTTTCGATATCCAAAGTGATGAGCGGCGAGCGAAATCCTGGCCACACCCAGCCTCCGAACATAAAGCTACTTACGTATGCTGACGGAAAACCCCTTAAATCATAAAAACATCGATGGTAGTTACCACTCGAGAACCCTAATTTCCCGACTCACACCGGCGAAGATACTAAATTGGGTTTGCGGGTGGCGCGTTGGCTATCCCGTTTTCACCTCTAAGGGCACGAGCTGTTGCCGCAAAGTTAGAACCGCGGACTACTGAATTCTTGGCTGATAGTGTTCGGCGCCTTCCTGGGTGAGCAGCCCGAACAGATTTTCGACCCTGGGCCGGAACACATGAGGAGCTTGCGTCTAGGGTTG"
S <- LCS_backtracer(v,w)

edit_distance <- function(v, w) {
  v <- unlist(strsplit(v, ""))
  w <- unlist(strsplit(w, ""))
  V <- length(v)
  W <- length(w)
  
  # Initialize the DP matrix
  s <- matrix(0, nrow = V + 1, ncol = W + 1)
  s[ ,1] <- 0:V     # deletions
  s[1, ] <- 0:W     # insertions
  
  # Fill the matrix
  for (i in 2:(V + 1)) {
    for (j in 2:(W + 1)) {
      cost <- ifelse(v[i - 1] == w[j - 1], 0, 1)  # substitution cost
      s[i, j] <- min(
        s[i - 1, j] + 1,         # deletion
        s[i, j - 1] + 1,         # insertion
        s[i - 1, j - 1] + cost   # substitution / match
      )
    }
  }
  
  return(s[V + 1, W + 1])
}
S <- edit_distance(v,w)
